### ISSUE TITLE
seal/libs下有okhttp的jar包，但是项目为什么还是使用的已经弃用的apache的http框架？

### ISSUE THREAD

**Issue by scdqs** [sealtalk/sealtalk-android#11]
seal/libs下有okhttp的jar包，但是项目为什么还是使用的已经弃用的apache的http框架？
是否能删除这个jar包和他关联的okio包？
或者是否能替换当前的http请求框架为okhttp？
如果不能替换，是处于什么原因不能替换呢？
能否使用Stetho查看当前框架的请求信息？

**Comment by 13120241790** [comment]
okhttp 是七牛云 sdk 必须依赖的 jar ，删除上传头像等功能无法使用 编译应该通过不了。这个 demo 只是演示 demo  http 的交互可以替换 okhttp 只是修改工作量比较大。
