### ISSUE TITLE
聊天界面点击加号按钮没有视屏通话和语音通话按钮

### ISSUE THREAD

**Issue by nievita** [sealtalk/sealtalk-android#13]
聊天界面点击加号按钮没有视屏通话和语音通话按钮

RongCallManager.class line 1651
String info = this.libStub.getVoIPCallInfo();
{"strategy":1,"callEngine":[{"engineType":1,"vendorKey":"a389de90728f409dbbbb6f682bdbd77e","signKey":"","blinkCMPServer":null,"blinkSnifferServer":null}]}

RongCallManager.class line 1667
if (CallEngineType.valueOf(object.optInt("engineType")).equals(CallEngineType.ENGINE_TYPE_BLINK)) 
判断逻辑不成立导致返回false

**Comment by JennyZhou918** [comment]
麻烦在最新版本上再试一下。
