### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by lhholylight** [sealtalk/sealtalk-android#19]
token获取成功，调用RongIM.connect(loginToken, callback)后返回[RC:L-connect-R]: {"ptid":"10802-1*","code":-1002}

**Comment by min476** [comment]
我也遇到了这个问题，把targetSdkVersion改小于24就可以了  
参考：https://support.rongcloud.cn/ks/NTQw

**Comment by lhholylight** [comment]
@min476 好的，解决了，谢谢
