### ISSUE TITLE
官方Demo在小米手机上进程被杀后 收到不到消息了

### ISSUE THREAD

**Issue by hjgang** [sealtalk/sealtalk-android#2]
官方Demo在小米手机上进程被杀后 收到不到消息这个bug什么时候能修复？

**Comment by iielse** [comment]
你用了小米推送吗？

**Comment by liusong** [comment]
@hjgang 我们后续做了优化，现在你更新以下新的 Demo 试一下呢？或者您看一下您的手机应用权限有没有打开？
