### ISSUE TITLE
请将CHANNAL改为app的发布渠道

### ISSUE THREAD

**Issue by Yeecz** [sealtalk/sealtalk-android#22]
[sealtalk-android/seal/src/main/AndroidManifest.xml](url)
请将CHANNAL改为app的发布渠道，第一次遇到不知道该怎么更改
`
<meta-data
            android:name="InstallChannel"
            android:value="CHANNAL"/>`

**Comment by 13120241790** [comment]
这个和 sdk 的使用没有关系，应该是应用打包相关的问题。seal 只支持开源学习使用 不支持打包到应用市场
