### ISSUE TITLE
导入到android studio中项目运行不起来

### ISSUE THREAD

**Issue by zhengxiaochuan** [sealtalk/sealtalk-android#3]
开发工具一直报错：Error:Execution failed for task ':seal:mergeDebugResources'.
> Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file D:\workspaces\AndroidStudioProjects\sealtalk-android\seal\build\intermediates\exploded-aar\sealtalk-android\Rong_Cloud_Android_IMKit_SDK_v2_7_2_stable_with_CallKit\unspecified\res\drawable-xhdpi-v4\rc_pb_file_download_progress_background.9.png into D:\workspaces\AndroidStudioProjects\sealtalk-android\seal\build\intermediates\res\merged\debug\drawable-xhdpi-v4\rc_pb_file_download_progress_background.9.png
请问这个到底是怎么回事，怎么解决？

**Comment by 13120241790** [comment]
你的 Android studio 环境 对 .9png 图片编译有问题  ，先 clean , rebuild 下项目 如果没效果  再把这个报错的.9 干掉 先让程序跑起来
