### ISSUE TITLE
魅族接收不到推送

### ISSUE THREAD

**Issue by bobohackbutter** [sealtalk/sealtalk-android#3]
魅蓝e3接收不到推送

**Comment by RongCloudYJH** [comment]
请问有没有集成魅族的第三方推送？其他魅族手机能收到推送吗？同时检查一下应用的自启动和通知权限有没有打开。

下面是魅族推送的集成文档，如果未集成请先按照此文档集成。
https://www.rongcloud.cn/docs/android_push.html#flyme
