### ISSUE TITLE
会话列表中群组标题和头像有时候会变成空。

### ISSUE THREAD

**Issue by jiawei-i** [sealtalk/sealtalk-android#32]
如果从会话列表的群组item点击去后就
![img_20170712_164053](https://user-images.githubusercontent.com/10320604/28109347-67ae25d0-6721-11e7-8317-e95ba0e0b1f4.png)

可以显示头像和标题。
但是如果在这个无法显示的群组会话里面强制杀掉应用后重新启动应用会话列表中还是不会显示这个群组item的名字和头像。

**Comment by 13120241790** [comment]
需要实现群组信息提供者，杀进程再进来有本地数据库缓存的信息 只要提供了数据杀了进程也应该有头像和昵称的展示

**Comment by jiawei-i** [comment]
是点击item就会显示头像和地址，但是杀掉进程就在登录回来就变回原来的没有头像和标题的样子。
