### ISSUE TITLE
Demo运行在华为P9 Plus和荣耀8等机型上，没法登录

### ISSUE THREAD

**Issue by drowtram** [sealtalk/sealtalk-android#36]
应该是在EMUI5.0上都没法登录，别的手机测试可以登录

**Comment by 13120241790** [comment]
我们这边华为的测试机登录全部没有问题 你那边不能登录 具体是什么表现？  有什么错误码 或者 错误提示

**Comment by drowtram** [comment]
![nXDns.gif](https://s1.ax1x.com/2017/09/15/nXDns.gif)
https://s1.ax1x.com/2017/09/15/nXDns.gif 屏幕效果你可以看看，就是点击登录后一直转圈，在非华为设备上就没有这个问题

**Comment by 13120241790** [comment]
抓一个从启动到登录然后登录不上的 logcat 日志过来的，注意有的华为手机需要开启日志开关 http://blog.csdn.net/sunleibo/article/details/7533819  类似这种。不开启开关获取的日志可能不全

**Comment by 13120241790** [comment]
有没有可能是你 WiFi 的问题 那个 GIF 上的 kb 大部分时候处于 0 的状态  有数据波动的状态值也很小没有超过 1KB的 ，你找个华为有 mobile 数据的手机再试试？

**Comment by drowtram** [comment]
网是没问题的，同一个wifi，非华为设备就能登录

**Comment by drowtram** [comment]
[log.txt](https://github.com/sealtalk/sealtalk-android/files/1306027/log.txt)
抓取了日志，你看看

**Comment by 13120241790** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlite.so" not found  
基于 Android  7.0 的手机需要加  libsqlite.so   你看看这个知识库  http://support.rongcloud.cn/kb/NTQw

**Comment by drowtram** [comment]
好的，可以登录了
