### ISSUE TITLE
状态提示bug

### ISSUE THREAD

**Issue by ncworm** [sealtalk/sealtalk-android#46]
把app按home键切到后台后，息屏放置一段时间，在回到app内。会话界面顶部就提示   “当前网络不可用，请检查你的网络设置”并且无法发送信息，这时是有网络的。这提示只有从新登陆，或者重新断开再连接网络才能恢复，请问这个怎么处理呢

**Comment by 13120241790** [comment]
具体情况需要具体分析 建议在官方开发者平台提交工单 那边处理效率更高
