### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by ainiyiwan** [sealtalk/sealtalk-android#53]
登录界面一直loading，无法进入主界面，但是从网站上下载的App可以，是区分处理了吗？还是哪一块儿注释了？

**Comment by amd110** [comment]
我也是遇到同样问题

**Comment by amd110** [comment]
切换到上一个tag 版本就可以登陆成功

**Comment by 13120241790** [comment]
我刚测试了最近的工程 旧账号登录 和 新账号注册+ 登录 目前都没有问题 感谢反馈
