### ISSUE TITLE
APP卸载重装之后，聊天列表的消息记录丢失了

### ISSUE THREAD

**Issue by sunkeding** [sealtalk/sealtalk-android#60]
已经是用的2.9.0 Dev版本的SDK，然后也已经开通了1、服务端实时消息路由 2、单群聊消息云存储3 、在线状态订阅4、广播消息和推送 5、多设备消息同步这几个高级功能了；卸载重装之后，消息列表记录丢失了

**Comment by 13120241790** [comment]
您好  ，到工单系统上提问吧 ，那边效率高一些 有专门的工程师给你解答
