### ISSUE TITLE
 RongIM.connect 无法回调

### ISSUE THREAD

**Issue by wxy520ll** [sealtalk/sealtalk-android#61]
把demo下载了。安装运行登录不上，我就是想看看 RongIM.connect 无法回调  心酸+心累

**Comment by amd110** [comment]
同样问题

**Comment by amd110** [comment]
切换到上一个tag 版本就可以进去了

**Comment by 13120241790** [comment]
@wxy520ll @amd110  谢谢反馈  我们查一下

**Comment by 13120241790** [comment]
@wxy520ll @amd110  我刚测试了一下 最近的工程 旧账号登录 新账号注册 + 登录 都没有问题
