### ISSUE TITLE
运行demo，无法进入登录页面

### ISSUE THREAD

**Issue by fengcaizhi** [sealtalk/sealtalk-android#7]

**Comment by huangruiLearn** [comment]
@fengcaizhi 
解决没

**Comment by caishuwei** [comment]
@huangruiLearn 
我发现异常在ApiClientMgr.onActivityResume方法里面
HuaweiApiClient类没有onResume方法，但他调用了。。。

然后我将App类里面的RongPushClient.registerHWPush(this);注释掉就可以了。

**Comment by jianghuihr** [comment]
@caishuwei 在魅族 Android 7.0.1 Flyme 7.0.1.0A 上直接闪退了，但是在华为 Android 8.1.0 EMUI 8.2.0 上成功进入登录页面了
