### ISSUE TITLE
CallLib没有提供x86的库文件

### ISSUE THREAD

**Issue by caishuwei** [sealtalk/sealtalk-android#8]
发现再安卓模拟器上跑不了，查看了一下编译出的apk，里面缺少CallLib的x86库文件，包括从官网下的sdk里面也是没有(只有armeabi-v7a arm64-v8a)，而文档说支持"armeabi-v7a", "x86"？是否现在已经不支持x86

**Comment by RongCloudYJH** [comment]
目前音视频不提供 x86,因为 armeabi-v7a 可以兼容 x86。 建议在模拟器上将 x86 的配置去掉，同时将 x86 对应的路径也删掉。
