### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by liuchenc** [sealtalk/sealtalk-android#9]
>  [ RongExceptionHandler ] uncaughtException
                                            java.lang.NoSuchMethodError: No virtual method onResume(Landroid/app/Activity;)V in class Lcom/huawei/hms/api/HuaweiApiClient; or its super classes (declaration of 'com.huawei.hms.api.HuaweiApiClient' appears in /data/app/cn.rongcloud.im-BmJkax3eju2xGwV8y_B-yg==/base.apk:classes2.dex)

**Comment by bughp** [comment]
我也是 报这个错，请问你解决了吗？

**Comment by caishuwei** [comment]
@bughp  可能是使用的华为推送sdk版本不对，注释掉App类里面华为推送的注册代码
https://github.com/sealtalk/sealtalk-android/issues/7#issuecomment-437281578

**Comment by 13120241790** [comment]
#7 已解决给出解决方案了 @bughp @liuchenc
